/** 审计动作常量。新加 action 时必须同步更新此处 */
export const AuditActions = {
  // 认证
  LOGIN_OK: 'LOGIN_OK',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER: 'REGISTER',

  // 号池
  POOL_TOKEN_REVEAL: 'POOL_TOKEN_REVEAL',
  POOL_ACCOUNT_CREATE: 'POOL_ACCOUNT_CREATE',
  POOL_ACCOUNT_UPDATE: 'POOL_ACCOUNT_UPDATE',
  POOL_ACCOUNT_DELETE: 'POOL_ACCOUNT_DELETE',

  // 订单
  ORDER_MARK_PAID: 'ORDER_MARK_PAID',
  ORDER_REDELIVER: 'ORDER_REDELIVER',
  ORDER_MANUAL_DELIVER: 'ORDER_MANUAL_DELIVER',
  ORDER_REFUND: 'ORDER_REFUND',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_DELETE: 'ORDER_DELETE',
  FORGE_ORDER_DELETE: 'FORGE_ORDER_DELETE',
  FORGE_QUOTA_ORDER_DELETE: 'FORGE_QUOTA_ORDER_DELETE',
  FORGE_QUOTA_CODE_VOID: 'FORGE_QUOTA_CODE_VOID',

  // 支付（高危事件）
  ALIPAY_AMOUNT_MISMATCH: 'ALIPAY_AMOUNT_MISMATCH', // 金额不一致（攻击 / bug 警报）
  ALIPAY_SIGN_FAIL: 'ALIPAY_SIGN_FAIL',
  ALIPAY_SELLER_MISMATCH: 'ALIPAY_SELLER_MISMATCH',
  ALIPAY_MANUAL_QUERY: 'ALIPAY_MANUAL_QUERY',
  ALIPAY_MANUAL_REFUND: 'ALIPAY_MANUAL_REFUND',
  ALIPAY_AUTO_CLOSE: 'ALIPAY_AUTO_CLOSE',
  ALIPAY_AUTO_RECOVER: 'ALIPAY_AUTO_RECOVER', // notify 丢失，通过定时查询找回的订单

  // 卡密
  CARD_KEY_DELETE: 'CARD_KEY_DELETE',
  CARD_KEY_BULK_REMOVE: 'CARD_KEY_BULK_REMOVE',
  CARD_KEY_PURGE: 'CARD_KEY_PURGE',
  CARD_KEY_BULK_IMPORT: 'CARD_KEY_BULK_IMPORT',

  // 仓库（外部账号入库 / 分配到商品）
  WAREHOUSE_BULK_IMPORT: 'WAREHOUSE_BULK_IMPORT',
  WAREHOUSE_MANUAL_ADD: 'WAREHOUSE_MANUAL_ADD',
  WAREHOUSE_ASSIGN: 'WAREHOUSE_ASSIGN',
  WAREHOUSE_UNASSIGN: 'WAREHOUSE_UNASSIGN',
  WAREHOUSE_DELETE: 'WAREHOUSE_DELETE',
  WAREHOUSE_REFUND_SET: 'WAREHOUSE_REFUND_SET',       // 设置售出账号退款时间
  WAREHOUSE_REFUND_NOTIFY: 'WAREHOUSE_REFUND_NOTIFY', // 立即推送退款提醒到企微
  WAREHOUSE_REFUND_RUN: 'WAREHOUSE_REFUND_RUN',       // 手动执行 Cursor 退款

  // 订阅号池（cursor-jb 合并）
  CURSOR_SUB_PUSH: 'CURSOR_SUB_PUSH',       // 订阅账号推送到仓库
  CURSOR_SUB_MIGRATE: 'CURSOR_SUB_MIGRATE', // 迁移导入 cursor-jb 账号

  // 用户 / 资金
  USER_UPDATE: 'USER_UPDATE',
  BALANCE_ADJUST: 'BALANCE_ADJUST',
  BALANCE_RECHARGE: 'BALANCE_RECHARGE',            // 充值到账
  BALANCE_RECHARGE_AMOUNT_MISMATCH: 'BALANCE_RECHARGE_AMOUNT_MISMATCH', // 充值金额校验失败（高危）
  BALANCE_RECHARGE_REFUND: 'BALANCE_RECHARGE_REFUND', // 充值退款

  // 站点设置
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  // 商品
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  // VIP
  VIP_UPGRADE: 'VIP_UPGRADE',                    // 用户达到充值阈值自动升级
  VIP_MANUAL_SET: 'VIP_MANUAL_SET',              // 管理员手动调整等级
  VIP_CONFIG_UPDATE: 'VIP_CONFIG_UPDATE',        // 修改等级阈值/默认折扣
  VIP_DISCOUNT_UPDATE: 'VIP_DISCOUNT_UPDATE',    // 修改商品级折扣
  VIP_USER_DISCOUNT_SET: 'VIP_USER_DISCOUNT_SET', // 设置/清除用户专属折扣
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];

/** 给前端展示用的中文映射 */
export const AuditActionLabels: Record<string, string> = {
  LOGIN_OK: '登录成功',
  LOGIN_FAIL: '登录失败',
  REGISTER: '注册',
  POOL_TOKEN_REVEAL: '查看号池 Token',
  POOL_ACCOUNT_CREATE: '新建号池账号',
  POOL_ACCOUNT_UPDATE: '编辑号池账号',
  POOL_ACCOUNT_DELETE: '删除号池账号',
  ORDER_MARK_PAID: '订单标记已支付',
  ORDER_REDELIVER: '订单补发',
  ORDER_MANUAL_DELIVER: '手动发货',
  ORDER_REFUND: '订单退款',
  ORDER_CANCEL: '订单取消',
  ORDER_DELETE: '删除订单',
  FORGE_ORDER_DELETE: '删除三方订单',
  FORGE_QUOTA_ORDER_DELETE: '删除额度包订单',
  FORGE_QUOTA_CODE_VOID: '作废额度包兑换码',
  ALIPAY_AMOUNT_MISMATCH: '支付宝金额不一致',
  ALIPAY_SIGN_FAIL: '支付宝验签失败',
  ALIPAY_SELLER_MISMATCH: '支付宝商户号不一致',
  ALIPAY_MANUAL_QUERY: '主动查询支付宝订单',
  ALIPAY_MANUAL_REFUND: '支付宝退款',
  ALIPAY_AUTO_CLOSE: '关闭支付宝订单',
  ALIPAY_AUTO_RECOVER: 'notify 丢失自动找回',
  CARD_KEY_DELETE: '删除卡密',
  CARD_KEY_BULK_REMOVE: '批量删除卡密',
  CARD_KEY_PURGE: '清理卡密',
  CARD_KEY_BULK_IMPORT: '导入卡密',
  WAREHOUSE_BULK_IMPORT: '仓库批量入库',
  WAREHOUSE_MANUAL_ADD: '仓库手动添加账号',
  WAREHOUSE_ASSIGN: '仓库账号分配到商品',
  WAREHOUSE_UNASSIGN: '撤回仓库账号分配',
  WAREHOUSE_DELETE: '删除仓库账号',
  WAREHOUSE_REFUND_SET: '设置售出账号退款时间',
  WAREHOUSE_REFUND_NOTIFY: '推送退款提醒到企业微信',
  WAREHOUSE_REFUND_RUN: '执行 Cursor 自动退款',
  CURSOR_SUB_PUSH: '订阅账号推送到仓库',
  CURSOR_SUB_MIGRATE: '迁移导入订阅账号',
  USER_UPDATE: '修改用户',
  BALANCE_ADJUST: '调整余额',
  BALANCE_RECHARGE: '账户充值到账',
  BALANCE_RECHARGE_AMOUNT_MISMATCH: '充值金额校验失败',
  BALANCE_RECHARGE_REFUND: '充值退款',
  SETTINGS_UPDATE: '修改站点设置',
  PRODUCT_DELETE: '删除商品',
  VIP_UPGRADE: 'VIP 自动升级',
  VIP_MANUAL_SET: 'VIP 手动调级',
  VIP_CONFIG_UPDATE: '修改 VIP 等级配置',
  VIP_DISCOUNT_UPDATE: '修改商品折扣',
  VIP_USER_DISCOUNT_SET: '设置用户专属折扣',
};
