/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPageHeader: typeof import('./components/admin/AdminPageHeader.vue')['default']
    AdminSearchInput: typeof import('./components/admin/AdminSearchInput.vue')['default']
    AnnouncementBanner: typeof import('./components/AnnouncementBanner.vue')['default']
    AnnouncementDialog: typeof import('./components/AnnouncementDialog.vue')['default']
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    BrandButton: typeof import('./components/BrandButton.vue')['default']
    Captcha: typeof import('./components/Captcha.vue')['default']
    CursorQuotaReportDrawer: typeof import('./components/admin/CursorQuotaReportDrawer.vue')['default']
    CursorSubDetailDrawer: typeof import('./components/admin/CursorSubDetailDrawer.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EmailCodeBox: typeof import('./components/EmailCodeBox.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ForgeOrderDetailDrawer: typeof import('./components/admin/ForgeOrderDetailDrawer.vue')['default']
    ForgeQuotaOrderDetailDrawer: typeof import('./components/admin/ForgeQuotaOrderDetailDrawer.vue')['default']
    OrderDetailDrawer: typeof import('./components/admin/OrderDetailDrawer.vue')['default']
    OrderStatusBadge: typeof import('./components/OrderStatusBadge.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    RichContent: typeof import('./components/RichContent.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    StatusTag: typeof import('./components/admin/StatusTag.vue')['default']
    TopProgress: typeof import('./components/TopProgress.vue')['default']
    UserDetailDrawer: typeof import('./components/admin/UserDetailDrawer.vue')['default']
    WarehouseDetailDrawer: typeof import('./components/admin/WarehouseDetailDrawer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
