/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPageHeader: typeof import('./components/admin/AdminPageHeader.vue')['default']
    AnnouncementDialog: typeof import('./components/AnnouncementDialog.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    OrderDetailDrawer: typeof import('./components/admin/OrderDetailDrawer.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./components/admin/StatusTag.vue')['default']
  }
}
